language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

install:
   - mkdir -p build/bin
   - mkdir -p build/logs
   - curl -sS https://getcomposer.org/installer | php -- --install-dir=./build/bin
   - php ./build/bin/composer.phar install

script:
   - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml tests/

after_script:
   - ./vendor/bin/coveralls -v
   - CODECLIMATE_REPO_TOKEN=ff5c83c9b8ac279c3c1bf3452765f4b9022ed5d308b506d24b11e188e7ae4388 ./vendor/bin/test-reporter
   - wget --output-document=build/bin/ocular.phar https://scrutinizer-ci.com/ocular.phar
   - php ./build/bin/ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
